import type { TargetAgent } from "@/lib/skills/recommendations";

// All three native-skill previews use the open Agent Skills frontmatter contract
// (`name` + `description`). Governance — status, version, last_verified, disclaimer,
// sources — lives in the markdown body as a footer, not in undocumented frontmatter.
const NATIVE_SKILL_BODY = `# ZATCA Phase 2

> Engineering guidance, not legal advice. Verify every rule against the
> official ZATCA documentation linked below.

## When this applies

You are working on a product that issues invoices to Saudi customers
and is using **Node.js** as the backend stack.

## Non-negotiables

- Every B2B invoice must be cleared with ZATCA **before** being
  delivered to the buyer.
- Every B2C invoice must be reported within **24 hours** of issuance.
- Every invoice XML must include a cryptographic stamp derived from
  the taxpayer's CSID certificate.

## Your stack specifics

\`\`\`ts
// Use the UBL builder — don't hand-roll the XML.
import { buildInvoiceXML, stamp } from "@zatca/ubl";
\`\`\`

See references/zatca-xml-sample.xml for a full sample.

_Version: 0.4.2 · Last verified: 2026-03-18 · Status: maintainer-reviewed_
`;

const CLAUDE_SAMPLE = `---
name: zatca-phase2
description: ZATCA Phase 2 e-invoicing rules for Saudi Arabia
---

${NATIVE_SKILL_BODY}`;

const CURSOR_SAMPLE = `---
name: zatca-phase2
description: ZATCA Phase 2 e-invoicing rules for Saudi Arabia
---

${NATIVE_SKILL_BODY}`;

const CODEX_SAMPLE = `---
name: zatca-phase2
description: ZATCA Phase 2 e-invoicing rules for Saudi Arabia
---

${NATIVE_SKILL_BODY}`;

const GENERIC_SAMPLE = `# AGENTS.md

_Generated by Wathba Skills · AGENTS.md_

Portable repository guidance for any agent that reads AGENTS.md. It
aggregates the skills selected during generation.

---

## ZATCA Phase 2 e-invoicing · v0.4.2 · reviewed

> Engineering guidance, not legal advice. Verify each rule against the official sources below.

- Clear B2B invoices before delivery.
- Report B2C invoices within 24 hours.
- Stamp every invoice XML with CSID.

_Version: 0.4.2 · Last verified: 2026-03-18_

## Secrets baseline · v1.0.0 · reviewed

- Never commit .env files.
- Rotate any secret that was ever in git history.
- Prefer the chosen secret manager over .env files.

_Version: 1.0.0 · Last verified: 2026-02-04_

## Testability check · v0.4.0 · community

- Isolate side effects at the edges.
- No module-level singletons for mutable state.
- Every new feature ships with at least one seam test.

_Version: 0.4.0 · Last verified: 2026-01-28_
`;

export const SAMPLE_PREVIEW_BODIES: Record<TargetAgent, string> = {
  "claude-code": CLAUDE_SAMPLE,
  cursor: CURSOR_SAMPLE,
  codex: CODEX_SAMPLE,
  "agents-md": GENERIC_SAMPLE,
};

// The sample path each target expects, shown in the UI as a filename caption so users
// can sanity-check against the docs contract before they generate the real pack.
export const SAMPLE_PREVIEW_PATHS: Record<TargetAgent, string> = {
  "claude-code": ".claude/skills/zatca-phase2/SKILL.md",
  cursor: ".cursor/skills/zatca-phase2/SKILL.md",
  codex: ".agents/skills/zatca-phase2/SKILL.md",
  "agents-md": "AGENTS.md",
};

export function resolveActiveTarget(
  availableTargets: readonly TargetAgent[],
  current: TargetAgent | null,
): TargetAgent | null {
  if (availableTargets.length === 0) return null;
  if (current && availableTargets.includes(current)) return current;
  return availableTargets[0];
}
