import type { TargetAgent } from "@/lib/skills/recommendations";

const CLAUDE_SAMPLE = `---
name: zatca-phase2
description: ZATCA Phase 2 e-invoicing rules for Saudi Arabia
version: 0.4.2
status: reviewed
last_verified: 2026-03-18
---

# ZATCA Phase 2

> This is engineering guidance, not legal advice. Verify every
> rule against the official ZATCA documentation linked in /sources.

## When this applies

You are working on a product that issues invoices to Saudi customers
and is using **Node.js** as the backend stack.

## Non-negotiables

- Every B2B invoice must be cleared with ZATCA **before** being
  delivered to the buyer.
- Every B2C invoice must be reported within **24 hours** of issuance.
- Every invoice XML must include a cryptographic stamp derived from
  the taxpayer's CSID certificate.

## Your stack specifics

\`\`\`ts
// Use the UBL builder — don't hand-roll the XML.
import { buildInvoiceXML, stamp } from "@zatca/ubl";
\`\`\`

See references/invoice-b2c.xml for a full sample.
`;

const CURSOR_SAMPLE = `---
description: ZATCA Phase 2 e-invoicing rules (Saudi Arabia)
globs: **/invoice*, **/billing/**
alwaysApply: false
---
# ZATCA Phase 2 — Cursor rule

> Engineering guidance only. Not legal advice. Check /sources.

- Every B2B invoice is cleared with ZATCA before delivery.
- Every B2C invoice is reported within 24 hours.
- Stamp every invoice XML using the CSID certificate.

## Note
Helper scripts are read-only guidance in Cursor. See full skill at
github.com/wathba-skills/skills/saudi/zatca-phase2.
`;

const CODEX_SAMPLE = `# AGENTS.md

_Generated by Wathba Skills_

This file tells your agent the rules of this repository. It
aggregates the skills selected during generation.

---

## ZATCA Phase 2 e-invoicing  ·  v0.4.2  ·  reviewed

> Engineering guidance, not legal advice.

- Clear B2B invoices before delivery.
- Report B2C invoices within 24 hours.
- Stamp every invoice XML with CSID.

## Secrets baseline  ·  v1.0.0  ·  reviewed

- Never commit .env files.
- Rotate any secret that was ever in git history.
- Prefer the chosen secret manager over .env files.

## Auth boundary isolation  ·  v0.3.0  ·  community

- Keep admin code in a separate folder or package.
- Never check admin status inline in a user-facing handler.
- Audit-log privileged actions.

## Testability check  ·  v0.4.0  ·  community

- Isolate side effects at the edges.
- No module-level singletons for mutable state.
- Every new feature ships with at least one seam test.
`;

const GENERIC_SAMPLE = `# AGENTS.md

_Generated by Wathba Skills · AGENTS.md_

Portable repository guidance for any agent that reads AGENTS.md. It
aggregates the skills selected during generation.

---

## ZATCA Phase 2 e-invoicing · v0.4.2 · reviewed

> Engineering guidance, not legal advice. Verify each rule against the official sources below.

- Clear B2B invoices before delivery.
- Report B2C invoices within 24 hours.
- Stamp every invoice XML with CSID.

_Version: 0.4.2 · Last verified: 2026-03-18_

## Secrets baseline · v1.0.0 · reviewed

- Never commit .env files.
- Rotate any secret that was ever in git history.
- Prefer the chosen secret manager over .env files.

_Version: 1.0.0 · Last verified: 2026-02-04_

## Testability check · v0.4.0 · community

- Isolate side effects at the edges.
- No module-level singletons for mutable state.
- Every new feature ships with at least one seam test.

_Version: 0.4.0 · Last verified: 2026-01-28_
`;

export const SAMPLE_PREVIEW_BODIES: Record<TargetAgent, string> = {
  "claude-code": CLAUDE_SAMPLE,
  cursor: CURSOR_SAMPLE,
  codex: CODEX_SAMPLE,
  "agents-md": GENERIC_SAMPLE,
};

export function resolveActiveTarget(
  availableTargets: readonly TargetAgent[],
  current: TargetAgent | null,
): TargetAgent | null {
  if (availableTargets.length === 0) return null;
  if (current && availableTargets.includes(current)) return current;
  return availableTargets[0];
}
