import type { GeneratedSkill } from "@/lib/skills/generated";

import type { RenderedFile } from "@/lib/generate/adapters/claude-code";
import type { SkillResolution } from "@/lib/generate/resolve-markdown";

const CODEX_PATH = "AGENTS.md";

const STATUS_LABEL: Record<GeneratedSkill["status"], string> = {
  "maintainer-reviewed": "reviewed",
  "community-maintained": "community",
  draft: "draft",
};

const CODEX_HEADER = `# AGENTS.md

_Generated by Wathba Skills · Codex_

This file tells your agent the rules of this repository. It
aggregates the skills selected during generation.`;

function renderSkillSection(
  skill: GeneratedSkill,
  resolvedBody: string,
): string {
  const name = skill.name.en;
  const statusLabel = STATUS_LABEL[skill.status];
  const heading = `## ${name} · v${skill.version} · ${statusLabel}`;
  const body = resolvedBody.replace(/\s+$/, "");
  const segments: string[] = [heading];
  if (skill.disclaimer) {
    segments.push(
      "> Engineering guidance, not legal advice. Verify each rule against the official sources below.",
    );
  }
  if (body.length > 0) {
    segments.push(body);
  }
  segments.push(
    `_Version: ${skill.version} · Last verified: ${skill.lastVerified}_`,
  );
  if (skill.sources.length > 0) {
    const sourceLines = skill.sources.map(
      (source) => `- [${source.title}](${source.url})`,
    );
    segments.push(["_Sources:_", ...sourceLines].join("\n"));
  }
  return segments.join("\n\n");
}

export function renderCodexFiles(
  skills: readonly GeneratedSkill[],
  resolutions: readonly SkillResolution[],
): RenderedFile[] {
  if (skills.length === 0) return [];
  const resolutionById = new Map(
    resolutions.map((resolution) => [resolution.skillId, resolution]),
  );
  const sections = skills.map((skill) => {
    const resolution = resolutionById.get(skill.id);
    const body = resolution ? resolution.body : skill.body;
    return renderSkillSection(skill, body);
  });
  const content = `${[CODEX_HEADER, "---", ...sections].join("\n\n")}\n`;
  return [{ path: CODEX_PATH, content }];
}

export function renderCodexPaths(
  skills: readonly GeneratedSkill[],
): string[] {
  return renderCodexFiles(skills, []).map((file) => file.path);
}
