import { describe, expect, it } from "vitest";

import { renderCodexFiles, renderCodexPaths } from "@/lib/generate/adapters/codex";
import type { SkillResolution } from "@/lib/generate/resolve-markdown";
import type { GeneratedSkill } from "@/lib/skills/generated";

function makeSkill(
  overrides: Partial<GeneratedSkill> & Pick<GeneratedSkill, "id" | "slug">,
): GeneratedSkill {
  const { id, slug, ...rest } = overrides;
  return {
    id,
    name: { en: id, ar: id },
    summary: { en: `${id} summary`, ar: `${id} ملخص` },
    slug,
    version: "0.1.0",
    category: "architecture",
    region: null,
    targets: ["codex"],
    status: "draft",
    lastVerified: "2026-01-01",
    maintainers: [],
    sources: [],
    disclaimer: false,
    variables: [],
    triggers: [],
    body: "",
    directory: slug,
    references: [],
    scripts: [],
    ...rest,
  };
}

function makeResolution(
  overrides: Partial<SkillResolution> &
    Pick<SkillResolution, "skillId" | "slug" | "body">,
): SkillResolution {
  return {
    missing: [],
    ...overrides,
  };
}

describe("renderCodexFiles", () => {
  it("returns an empty list when no skills are active", () => {
    expect(renderCodexFiles([], [])).toEqual([]);
    expect(renderCodexPaths([])).toEqual([]);
  });

  it("emits a single AGENTS.md file aggregating every selected skill", () => {
    const a = makeSkill({
      id: "a",
      slug: "alpha",
      name: { en: "Alpha skill", ar: "ألفا" },
    });
    const b = makeSkill({
      id: "b",
      slug: "beta",
      name: { en: "Beta skill", ar: "بيتا" },
    });
    const files = renderCodexFiles(
      [a, b],
      [
        makeResolution({ skillId: "a", slug: "alpha", body: "A body" }),
        makeResolution({ skillId: "b", slug: "beta", body: "B body" }),
      ],
    );
    expect(files).toHaveLength(1);
    expect(files[0].path).toBe("AGENTS.md");
    expect(renderCodexPaths([a, b])).toEqual(["AGENTS.md"]);
  });

  it("renders a top-level header and a section per skill with version and status", () => {
    const skill = makeSkill({
      id: "a",
      slug: "alpha",
      name: { en: "Alpha skill", ar: "ألفا" },
      version: "1.2.3",
      status: "maintainer-reviewed",
      lastVerified: "2026-02-10",
    });
    const [file] = renderCodexFiles(
      [skill],
      [makeResolution({ skillId: "a", slug: "alpha", body: "Hello world." })],
    );
    expect(file.content.startsWith("# AGENTS.md")).toBe(true);
    expect(file.content).toContain("_Generated by Wathba Skills · Codex_");
    expect(file.content).toContain("## Alpha skill · v1.2.3 · reviewed");
    expect(file.content).toContain("Hello world.");
    expect(file.content).toContain(
      "_Version: 1.2.3 · Last verified: 2026-02-10_",
    );
    expect(file.content.endsWith("\n")).toBe(true);
  });

  it("maps status strings to human-readable labels", () => {
    const reviewed = makeSkill({
      id: "r",
      slug: "r",
      status: "maintainer-reviewed",
    });
    const community = makeSkill({
      id: "c",
      slug: "c",
      status: "community-maintained",
    });
    const draft = makeSkill({ id: "d", slug: "d", status: "draft" });
    const [file] = renderCodexFiles(
      [reviewed, community, draft],
      [
        makeResolution({ skillId: "r", slug: "r", body: "r" }),
        makeResolution({ skillId: "c", slug: "c", body: "c" }),
        makeResolution({ skillId: "d", slug: "d", body: "d" }),
      ],
    );
    expect(file.content).toContain("· reviewed");
    expect(file.content).toContain("· community");
    expect(file.content).toContain("· draft");
  });

  it("prepends a disclaimer callout on skills that declare one", () => {
    const skill = makeSkill({
      id: "a",
      slug: "alpha",
      disclaimer: true,
    });
    const [file] = renderCodexFiles(
      [skill],
      [makeResolution({ skillId: "a", slug: "alpha", body: "body" })],
    );
    expect(file.content).toContain(
      "> Engineering guidance, not legal advice.",
    );
  });

  it("omits the disclaimer callout when disclaimer is false", () => {
    const skill = makeSkill({ id: "a", slug: "alpha", disclaimer: false });
    const [file] = renderCodexFiles(
      [skill],
      [makeResolution({ skillId: "a", slug: "alpha", body: "body" })],
    );
    expect(file.content).not.toContain("not legal advice");
  });

  it("renders a Sources list when the skill has sources", () => {
    const skill = makeSkill({
      id: "a",
      slug: "alpha",
      sources: [
        {
          title: "ZATCA docs",
          url: "https://zatca.gov.sa/docs",
          accessed: "2026-01-01",
        },
        {
          title: "UBL 2.1",
          url: "https://example.com/ubl",
          accessed: "2026-01-02",
        },
      ],
    });
    const [file] = renderCodexFiles(
      [skill],
      [makeResolution({ skillId: "a", slug: "alpha", body: "body" })],
    );
    expect(file.content).toContain("_Sources:_");
    expect(file.content).toContain("- [ZATCA docs](https://zatca.gov.sa/docs)");
    expect(file.content).toContain("- [UBL 2.1](https://example.com/ubl)");
  });

  it("omits the Sources list when there are no sources", () => {
    const skill = makeSkill({ id: "a", slug: "alpha", sources: [] });
    const [file] = renderCodexFiles(
      [skill],
      [makeResolution({ skillId: "a", slug: "alpha", body: "body" })],
    );
    expect(file.content).not.toContain("_Sources:_");
  });

  it("preserves the order of selected skills", () => {
    const a = makeSkill({
      id: "a",
      slug: "alpha",
      name: { en: "Alpha", ar: "ألفا" },
    });
    const b = makeSkill({
      id: "b",
      slug: "beta",
      name: { en: "Beta", ar: "بيتا" },
    });
    const c = makeSkill({
      id: "c",
      slug: "gamma",
      name: { en: "Gamma", ar: "غاما" },
    });
    const [file] = renderCodexFiles(
      [c, a, b],
      [
        makeResolution({ skillId: "a", slug: "alpha", body: "A" }),
        makeResolution({ skillId: "b", slug: "beta", body: "B" }),
        makeResolution({ skillId: "c", slug: "gamma", body: "C" }),
      ],
    );
    const alphaIdx = file.content.indexOf("## Alpha");
    const betaIdx = file.content.indexOf("## Beta");
    const gammaIdx = file.content.indexOf("## Gamma");
    expect(gammaIdx).toBeGreaterThan(-1);
    expect(alphaIdx).toBeGreaterThan(gammaIdx);
    expect(betaIdx).toBeGreaterThan(alphaIdx);
  });

  it("falls back to the raw skill body when a resolution is missing", () => {
    const skill = makeSkill({
      id: "a",
      slug: "alpha",
      body: "# Raw body\n{{stack}}",
    });
    const [file] = renderCodexFiles([skill], []);
    expect(file.content).toContain("# Raw body");
    expect(file.content).toContain("{{stack}}");
  });

  it("produces identical output for identical inputs", () => {
    const skill = makeSkill({
      id: "a",
      slug: "alpha",
      disclaimer: true,
      sources: [
        { title: "Docs", url: "https://x.test", accessed: "2026-01-01" },
      ],
    });
    const a = renderCodexFiles(
      [skill],
      [makeResolution({ skillId: "a", slug: "alpha", body: "body" })],
    );
    const b = renderCodexFiles(
      [skill],
      [makeResolution({ skillId: "a", slug: "alpha", body: "body" })],
    );
    expect(a[0].content).toBe(b[0].content);
  });
});
