// Asserts the shape of the generated `.claude-plugin/marketplace.json` and
// `plugins/wathba-skills/.claude-plugin/plugin.json` against the Claude Code
// plugin contract (https://code.claude.com/docs/en/plugin-marketplaces).
// These are regenerated by `pnpm generate:plugin-dist`; this test catches
// contract drift (reserved names, wrong fields, broken source paths).

import { readFileSync, readdirSync } from "node:fs";
import path from "node:path";

import { describe, expect, it } from "vitest";

const REPO_ROOT = path.resolve(__dirname, "../../../..");
const MARKETPLACE_PATH = path.join(REPO_ROOT, ".claude-plugin/marketplace.json");
const PLUGIN_DIR = path.join(REPO_ROOT, "plugins/wathba-skills");
const PLUGIN_MANIFEST_PATH = path.join(PLUGIN_DIR, ".claude-plugin/plugin.json");

// Names reserved for official Anthropic use per the marketplaces docs.
const RESERVED_MARKETPLACE_NAMES = new Set([
  "claude-code-marketplace",
  "claude-code-plugins",
  "claude-plugins-official",
  "anthropic-marketplace",
  "anthropic-plugins",
  "agent-skills",
  "knowledge-work-plugins",
  "life-sciences",
]);

function readJson(p: string): Record<string, unknown> {
  return JSON.parse(readFileSync(p, "utf8"));
}

describe("marketplace manifest (.claude-plugin/marketplace.json)", () => {
  const manifest = readJson(MARKETPLACE_PATH);

  it("has a kebab-case, non-reserved name", () => {
    expect(manifest.name).toMatch(/^[a-z0-9]+(-[a-z0-9]+)*$/);
    expect(RESERVED_MARKETPLACE_NAMES.has(manifest.name as string)).toBe(false);
  });

  it("declares an owner with at least a name", () => {
    expect(manifest.owner).toBeTruthy();
    expect((manifest.owner as Record<string, unknown>).name).toBeTypeOf("string");
  });

  it("pins pluginRoot to ./plugins so plugin entries can use bare source paths", () => {
    const metadata = manifest.metadata as Record<string, unknown> | undefined;
    expect(metadata?.pluginRoot).toBe("./plugins");
  });

  it("lists exactly one plugin entry (wathba-skills)", () => {
    const plugins = manifest.plugins as Array<Record<string, unknown>>;
    expect(Array.isArray(plugins)).toBe(true);
    expect(plugins).toHaveLength(1);
    const entry = plugins[0];
    expect(entry.name).toBe("wathba-skills");
    expect(entry.source).toBe("./wathba-skills");
    expect(entry.version).toMatch(/^\d+\.\d+\.\d+/);
  });

  it("plugin entry uses a relative source path starting with ./", () => {
    const entry = (manifest.plugins as Array<Record<string, unknown>>)[0];
    expect(typeof entry.source === "string" && (entry.source as string).startsWith("./")).toBe(
      true,
    );
  });
});

describe("plugin manifest (plugins/wathba-skills/.claude-plugin/plugin.json)", () => {
  const manifest = readJson(PLUGIN_MANIFEST_PATH);

  it("has name, version, description", () => {
    expect(manifest.name).toBe("wathba-skills");
    expect(manifest.version).toMatch(/^\d+\.\d+\.\d+/);
    expect(typeof manifest.description).toBe("string");
    expect((manifest.description as string).length).toBeGreaterThan(0);
  });

  it("registers skills via the default ./skills/ path so auto-discovery works", () => {
    const skills = manifest.skills as string[];
    expect(skills).toContain("./skills/");
  });

  it("registers commands via the default ./commands/ path", () => {
    const commands = manifest.commands as string[];
    expect(commands).toContain("./commands/");
  });

  it("does not redeclare marketplace-entry-only fields (category, strict)", () => {
    // `claude plugin validate` warns that these belong in the marketplace entry
    // and are ignored when placed in plugin.json. We keep them out entirely.
    expect(manifest).not.toHaveProperty("category");
    expect(manifest).not.toHaveProperty("strict");
  });
});

describe("generated plugin tree", () => {
  it("every skill ships a SKILL.md at skills/<slug>/SKILL.md", () => {
    const skillDirs = readdirSync(path.join(PLUGIN_DIR, "skills"));
    expect(skillDirs.length).toBeGreaterThan(0);
    for (const slug of skillDirs) {
      const skillMd = path.join(PLUGIN_DIR, "skills", slug, "SKILL.md");
      expect(() => readFileSync(skillMd, "utf8"), `missing ${skillMd}`).not.toThrow();
    }
  });

  it("slugs are globally unique (flattened into skills/<slug>/)", () => {
    const skillDirs = readdirSync(path.join(PLUGIN_DIR, "skills"));
    expect(new Set(skillDirs).size).toBe(skillDirs.length);
  });

  it("ships plugin-level commands", () => {
    const commands = readdirSync(path.join(PLUGIN_DIR, "commands"));
    expect(commands.length).toBeGreaterThan(0);
    for (const file of commands) {
      expect(file.endsWith(".md")).toBe(true);
    }
  });

  it("ships plugin-level docs", () => {
    const docs = readdirSync(path.join(PLUGIN_DIR, "docs"));
    expect(docs).toContain("installation.md");
    expect(docs).toContain("development.md");
    expect(docs).toContain("skills-overview.md");
  });

  it("marks the plugin dir as generated so the generator can safely clear it", () => {
    expect(() =>
      readFileSync(path.join(PLUGIN_DIR, ".generated"), "utf8"),
    ).not.toThrow();
  });
});
