import { promises as fs } from "node:fs";
import path from "node:path";
import yaml from "js-yaml";

import {
  canonicalSkillSchema,
  type CanonicalSkill,
} from "../packages/skill-schema/src/index";

type GeneratedSkill = {
  id: string;
  name: CanonicalSkill["name"];
  slug: string;
  version: string;
  category: CanonicalSkill["category"];
  region: CanonicalSkill["region"];
  targets: CanonicalSkill["targets"];
  status: CanonicalSkill["status"];
  lastVerified: string;
  maintainers: CanonicalSkill["maintainers"];
  sources: CanonicalSkill["sources"];
  disclaimer: boolean;
  variables: CanonicalSkill["variables"];
  triggers: CanonicalSkill["triggers"];
  body: string;
  directory: string;
  references: Array<{ path: string }>;
  scripts: Array<{ path: string }>;
};

const repoRoot = process.cwd();
const skillsRoot = path.join(repoRoot, "skills");
const outputFile = path.join(repoRoot, "apps/web/lib/skills/generated.ts");

async function walk(currentDir: string, matches: string[] = []): Promise<string[]> {
  const entries = await fs.readdir(currentDir, { withFileTypes: true });

  for (const entry of entries) {
    const entryPath = path.join(currentDir, entry.name);
    if (entry.isDirectory()) {
      await walk(entryPath, matches);
      continue;
    }

    if (entry.name === "skill.yaml") {
      matches.push(entryPath);
    }
  }

  return matches;
}

async function listRelativeFiles(directory: string): Promise<Array<{ path: string }>> {
  try {
    const entries = await fs.readdir(directory, { withFileTypes: true });
    return entries
      .filter((entry) => entry.isFile())
      .map((entry) => ({
        path: entry.name,
      }))
      .sort((left, right) => left.path.localeCompare(right.path));
  } catch {
    return [];
  }
}

async function loadSkill(skillYamlPath: string): Promise<GeneratedSkill> {
  const directory = path.dirname(skillYamlPath);
  const rawYaml = await fs.readFile(skillYamlPath, "utf8");
  const parsed = canonicalSkillSchema.parse(yaml.load(rawYaml));
  const body = await fs.readFile(path.join(directory, "SKILL.md"), "utf8");
  const references = await listRelativeFiles(path.join(directory, "references"));
  const scripts = await listRelativeFiles(path.join(directory, "scripts"));

  return {
    id: parsed.id,
    name: parsed.name,
    slug: parsed.slug,
    version: parsed.version,
    category: parsed.category,
    region: parsed.region,
    targets: parsed.targets,
    status: parsed.status,
    lastVerified: parsed.last_verified,
    maintainers: parsed.maintainers,
    sources: parsed.sources,
    disclaimer: parsed.disclaimer,
    variables: parsed.variables,
    triggers: parsed.triggers,
    body,
    directory: path.relative(skillsRoot, directory),
    references,
    scripts,
  };
}

async function main() {
  const skillYamlFiles = await walk(skillsRoot);
  const skills = await Promise.all(skillYamlFiles.map(loadSkill));
  skills.sort((left, right) => left.id.localeCompare(right.id));

  const typeDefinition = `export type GeneratedSkill = {
  id: string;
  name: { en: string; ar: string };
  slug: string;
  version: string;
  category: "compliance" | "security" | "architecture";
  region: string | null;
  targets: Array<"claude-code" | "cursor" | "codex" | "agents-md">;
  status: "maintainer-reviewed" | "community-maintained" | "draft";
  lastVerified: string;
  maintainers: Array<{ github: string }>;
  sources: Array<{ title: string; url: string; accessed: string }>;
  disclaimer: boolean;
  variables: Array<{
    name: string;
    label: { en: string; ar: string };
    type: "select" | "boolean" | "text";
    options?: string[];
  }>;
  triggers: Array<{ when: Record<string, string | number | boolean | null> }>;
  body: string;
  directory: string;
  references: Array<{ path: string }>;
  scripts: Array<{ path: string }>;
};`;

  const contents = `// This file is auto-generated by scripts/generate-skills.ts

${typeDefinition}

export const generatedSkills: GeneratedSkill[] = ${JSON.stringify(skills, null, 2)};

export const generatedSkillsById = Object.fromEntries(
  generatedSkills.map((skill) => [skill.id, skill]),
) as Record<string, GeneratedSkill>;
`;

  await fs.mkdir(path.dirname(outputFile), { recursive: true });
  await fs.writeFile(outputFile, contents, "utf8");
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
