import { promises as fs } from "node:fs";
import path from "node:path";

import {
  loadSkillsFromDirectory,
  SkillLoaderError,
  SkillValidationError,
} from "./lib/skill-loader";

const repoRoot = process.cwd();
const skillsRoot = path.join(repoRoot, "skills");
const outputFile = path.join(repoRoot, "apps/web/lib/skills/generated.ts");

async function main() {
  const skills = await loadSkillsFromDirectory({ skillsRoot, repoRoot });

  const typeDefinition = `export type SkillFile = {
  path: string;
  encoding: "utf-8" | "base64";
  content: string;
};

export type SkillLifecycle = "active" | "deprecated" | "archived";

export type GeneratedSkill = {
  id: string;
  name: { en: string; ar: string };
  summary?: { en: string; ar: string };
  slug: string;
  previousIds: string[];
  version: string;
  category: "compliance" | "security" | "architecture";
  region: string | null;
  targets: Array<"claude-code" | "cursor" | "codex" | "agents-md">;
  status: "maintainer-reviewed" | "community-maintained" | "draft";
  lifecycle: SkillLifecycle;
  replacementId: string | null;
  sunsetDate: string | null;
  lifecycleNote: { en: string; ar: string } | null;
  lastVerified: string;
  maintainers: Array<{ github: string }>;
  sources: Array<{ title: string; url: string; accessed: string }>;
  disclaimer: boolean;
  variables: Array<{
    name: string;
    label: { en: string; ar: string };
    type: "select" | "boolean" | "text";
    options?: string[];
  }>;
  triggers: Array<{ when: Record<string, string | number | boolean | null> }>;
  body: string;
  directory: string;
  files: SkillFile[];
  references: Array<{ path: string; content: string }>;
  scripts: Array<{ path: string; content: string }>;
};`;

  const contents = `// This file is auto-generated by scripts/generate-skills.ts

${typeDefinition}

export const generatedSkills: GeneratedSkill[] = ${JSON.stringify(skills, null, 2)};

export const generatedSkillsById = Object.fromEntries(
  generatedSkills.map((skill) => [skill.id, skill]),
) as Record<string, GeneratedSkill>;
`;

  await fs.mkdir(path.dirname(outputFile), { recursive: true });
  await fs.writeFile(outputFile, contents, "utf8");
}

main().catch((error) => {
  if (error instanceof SkillValidationError || error instanceof SkillLoaderError) {
    console.error(error.message);
  } else {
    console.error(error);
  }
  process.exitCode = 1;
});
